// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dreinnkeziuugsuwmbab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyZWlubmtleml1dWdzdXdtYmFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NzM2ODgsImV4cCI6MjA1NTE0OTY4OH0.pvBW3smeiedDkJBrc8XrN6CS_ozHGJG7jkiSxz-ir_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);